### ISSUE TITLE
Solution does not build

### ISSUE THREAD

**Issue by lilmidnit** [E-goi/sdk-csharp#1]
Lots of build errors, missing usings and improper constructors abound.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignPushContent.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\AdvancedReportCampaignsObject.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\AdvancedReportCampaignsObject.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignEmailContent.cs	38	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignEmailContent.cs	38	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignEmailRssContent.cs	38	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignEmailRssContent.cs	38	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignPushContent.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignSmartSmsPageContent.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignSmartSmsPageContent.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignSmsContent.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignSmsContent.cs	43	N/A
Error	CS0246	The type or namespace name 'DestinationFieldEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignVoiceSendRequest.cs	36	N/A
Error	CS0246	The type or namespace name 'DestinationFieldEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CampaignVoiceSendRequest.cs	36	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CellphoneSender.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\CellphoneSender.cs	43	N/A
Error	CS0100	The parameter name 'language' is a duplicate	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\ComplexList.cs	42	N/A
Error	CS0246	The type or namespace name 'ActionNameEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\ContactActivity.cs	36	N/A
Error	CS0246	The type or namespace name 'ActionNameEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\ContactActivity.cs	36	N/A
Error	CS0246	The type or namespace name 'StatusEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\ContactExtraFields.cs	36	N/A
Error	CS0246	The type or namespace name 'StatusEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\ContactExtraFields.cs	36	N/A
Error	CS0246	The type or namespace name 'StatusEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\ContactExtraFieldsBulk.cs	36	N/A
Error	CS0246	The type or namespace name 'StatusEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\ContactExtraFieldsBulk.cs	36	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\ContentVoice.cs	38	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\ContentVoice.cs	38	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\DeactivateContactsRequest.cs	38	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\DeactivateContactsRequest.cs	38	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\DeleteCampaignsConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\DeleteCampaignsConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\DeleteFieldsConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\DeleteFieldsConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\EmailSendSegment.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\EmailSendSegment.cs	43	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\EnableTeConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\EnableTeConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalAutommaticInfo.cs	135	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalAutommaticInfo.cs	135	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalAutommaticInfo.cs	135	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalAutommaticInfo.cs	135	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalAutommaticInfo.cs	160	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalAutommaticInfo.cs	167	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalInfo.cs	38	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalInfo.cs	38	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalInfo.cs	38	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalInfo.cs	38	N/A
Error	CS0246	The type or namespace name 'RuleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalInfo.cs	38	N/A
Error	CS0246	The type or namespace name 'RuleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalInfo.cs	38	N/A
Error	CS0246	The type or namespace name 'ConditionEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalInfo.cs	38	N/A
Error	CS0246	The type or namespace name 'ConditionEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalInfo.cs	38	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalInfo.cs	38	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalInfo.cs	38	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalManualInfo.cs	59	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalManualInfo.cs	59	N/A
Error	CS0246	The type or namespace name 'ModelBool' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\GoalManualInfo.cs	71	N/A
Error	CS0100	The parameter name 'cellphone' is a duplicate	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\NumericCellphoneSender.cs	42	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\OLimitContactsActionSend.cs	38	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\OLimitContactsActionSend.cs	38	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\OSegmentsActionSend.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\OSegmentsActionSend.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\OSegmentsWithoutContactActionSend.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\OSegmentsWithoutContactActionSend.cs	43	N/A
Error	CS0100	The parameter name 'phone' is a duplicate	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PhoneSender.cs	43	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PostCNameConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PostCNameConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PostContactsConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PostContactsConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PostListsConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PostListsConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PostProductsConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PostProductsConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PostWebpushSiteConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TitleEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PostWebpushSiteConflict.cs	36	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PushNotificationSoundSchema.cs	38	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\PushNotificationSoundSchema.cs	38	N/A
Error	CS0100	The parameter name 'contactId' is a duplicate	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\RequestItemsUnsubscribe.cs	37	N/A
Error	CS0100	The parameter name 'data' is a duplicate	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\SendEmailContact.cs	42	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\SmartSmsSegmentsActionSend.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\SmartSmsSegmentsActionSend.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\SmsSegmentsActionSend.cs	43	N/A
Error	CS0246	The type or namespace name 'TypeEnum' could not be found (are you missing a using directive or an assembly reference?)	org.egoi.client.api	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\Model\SmsSegmentsActionSend.cs	43	N/A
Error	CS0006	Metadata file 'C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api\bin\Debug\org.egoi.client.api.dll' could not be found	org.egoi.client.api.Test	C:\Users\Robert\Downloads\sdk-csharp-1.1.1RC1\sdk-csharp-1.1.1RC1\src\org.egoi.client.api.Test\CSC	1	N/A

**Comment by renato-gomes** [comment]
Hi,

Please try Version: 1.1.4
